# Generated by Django 4.2.3 on 2023-10-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_useraccount_status_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='accountid',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='mobile',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='nationalid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
