# Generated by Django 4.2.3 on 2023-10-14 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transactions_created_at_transactions_modified_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='transaction_id',
        ),
    ]
