# Generated by Django 4.2.3 on 2023-10-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_transactions_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='transaction_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
