# Generated by Django 4.2.3 on 2023-10-14 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_transactions_transaction_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='transaction_description',
        ),
    ]
